name: Gerar Cobrinha

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4   # versão atualizada

      - name: Gerar animação
        uses: Platane/snk@v3        # versão estável
        with:
          github_user_name: nathmdo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3   # versão atualizada
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
